#!/usr/bin/env python3
"""Render the markdown narrative report from a finalized state dict."""
from __future__ import annotations

import _io_utf8  # noqa: F401  (side effect: forces UTF-8 stdout/stderr on Windows)

SEV_ICON = {"critical": "🔴", "warning": "🟠", "info": "🟡"}
VERDICT_ICON = {
    "CLEAN": "✅",
    "MINOR_FLAGS": "🟢",
    "MIXED": "🟠",
    "FRAUD_LIKELY": "🔴",
}


def _fmt_flags(flags: list[dict]) -> str:
    if not flags:
        return "_No flags._\n"
    out = []
    order = {"critical": 0, "warning": 1, "info": 2}
    for f in sorted(flags, key=lambda x: order.get(x["severity"], 9)):
        out.append(
            f"- {SEV_ICON.get(f['severity'],'•')} **{f['code']}** "
            f"(−{f['penalty']}) — {f['detail']}"
        )
    return "\n".join(out) + "\n"


def render(state: dict) -> str:
    ch = state["channel"]
    sc = state["score"]
    ga, gb, gc = state["group_a"], state["group_b"], state["group_c"]
    icon = VERDICT_ICON.get(sc["verdict"], "")

    L = []
    L.append(f"# Channel Authenticity Report — {ch.get('channel_name','?')}")
    L.append("")
    L.append(
        f"**{icon} {sc['final_score']}/100 — {sc['verdict']}** · {sc['advice']}"
    )
    if sc["hard_override_applied"]:
        L.append("")
        L.append(
            f"> ⚠️ **Hard override applied** — {sc['advice']} Score capped "
            f"regardless of other group scores."
        )
    L.append("")
    L.append(
        f"Channel `{ch.get('id')}` · {ch.get('reach') or 0:,} subs · "
        f"cat {ch.get('content_category')} · lang `{ch.get('language')}` · "
        f"country `{ch.get('country')}` · "
        f"{'TPP' if ch.get('is_tl_channel') else 'non-TPP'} · "
        f"MSN join {ch.get('media_selling_network_join_date') or '—'}"
    )
    if state.get("focus_adlink"):
        fa = state["focus_adlink"]
        L.append(
            f"\nDrill-down adlink **{fa.get('id')}** — "
            f"status {fa.get('publish_status')}, price {fa.get('price')}, "
            f"video `{fa.get('video_id')}`"
        )
    L.append("")
    L.append("## Group scores (equal weight, mean = final)")
    L.append("")
    L.append("| Group | Score |")
    L.append("|---|---|")
    L.append(f"| A — Engagement & peer ratios | {sc['group_scores']['A_engagement']}/100 |")
    L.append(f"| B — View-curve time-series | {sc['group_scores']['B_view_curves']}/100 |")
    L.append(f"| C — Comment content | {sc['group_scores']['C_comments']}/100 |")
    L.append(f"| **Final (mean)** | **{sc['final_score']}/100** |")
    L.append("")

    L.append("## Group A — Engagement & peer ratios")
    L.append("")
    L.append(_fmt_flags(ga["flags"]))
    m = ga.get("metrics", {})
    if m:
        L.append(
            f"_Longform like rate {m.get('longform_like_rate',0)*100:.3f}%, "
            f"comment rate {m.get('longform_comment_rate',0)*100:.4f}%, "
            f"avg longform views {int(m.get('avg_longform_views',0)):,}, "
            f"views/subs {m.get('views_to_subs_ratio',0)*100:.0f}%._"
        )
    L.append("")

    L.append("## Group B — View-curve time-series")
    L.append("")
    L.append(_fmt_flags(gb["flags"]))
    vi = gb.get("metrics", {}).get("video_integrity")
    if vi:
        L.append(
            f"_Video integrity: {vi['tracked_articles']} tracked, "
            f"{vi['offline_count']} offline ({vi['offline_rate']*100:.0f}%), "
            f"{vi['unlisted_count']} unlisted, "
            f"{vi['scrub_view_share']*100:.0f}% of tracked views gone; "
            f"{vi['benign_removals']} benign removal(s) excluded._"
        )
    L.append("")

    L.append("## Group C — Comment content")
    L.append("")
    L.append(_fmt_flags(gc["flags"]))
    mc = gc.get("metrics", {})
    if mc:
        passes = mc.get("llm_passes")
        pass_note = ""
        if passes and passes > 1:
            per = mc.get("llm_per_pass_organic_share") or []
            pass_note = (
                f" (majority of {passes} passes; per-pass "
                f"{', '.join(f'{p*100:.0f}%' for p in per)})"
            )
        L.append(
            f"_Scraped {mc.get('videos_scraped',0)} videos / "
            f"{mc.get('scraped_total_views',0):,} views → "
            f"{mc.get('viewer_comments',0)} viewer comments. "
            f"LLM organic share: "
            f"{_pct(mc.get('llm_organic_share'))}{pass_note}._"
        )
    L.append("")
    L.append("---")
    L.append(
        "_Generated by the `tl-channel-authenticity` skill. Data via the "
        "ThoughtLeaders CLI; comments scraped fresh from YouTube._"
    )
    return "\n".join(L)


def _pct(v) -> str:
    return f"{v*100:.0f}%" if isinstance(v, (int, float)) else "n/a"


if __name__ == "__main__":
    import json
    import sys

    with open(sys.argv[1], encoding="utf-8") as fh:
        print(render(json.load(fh)))
