"""Generate shared MCP examples, check drift, and build a reproducible upload ZIP."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLUGIN = Path('plugins/thoughtleaders-youtube-data')
SOURCE = Path('skills/tl/references/elasticsearch-schema.md')
GENERATED = Path('skills/tl-mcp/references/query-examples.md')
HEADINGS = (
    'Search videos by sponsored brand mention',
    'Count sponsored mentions for a brand (size:0 + track_total_hits)',
    'Full-text search on title/summary/transcript',
)
# Explicit public bundle boundary. New files require a reviewed allowlist change.
FILES = (
    '.codex-plugin/plugin.json',
    '.mcp.json',
    'skills/tl-mcp/SKILL.md',
    'skills/tl-mcp/references/tool-selection.md',
    GENERATED.as_posix(),
)


def render_examples(source: str) -> str:
    """Extract only JSON, never private prose or executable CLI instructions."""
    chunks = [
        '# ES query structure examples\n\n'
        '<!-- Generated by scripts/build_mcp_plugin.py; do not edit. -->\n\n'
        f'Source: `{SOURCE.as_posix()}` in the ThoughtLeaders CLI repository.\n'
        'Only the selected JSON examples are reused; no schema catalogue is bundled.\n'
        'These are illustrative `query` bodies for `tl_db_es`, not complete tool calls.\n'
        'Fetch `tl_schema_es` first; current schema and tool definitions take precedence.\n'
        'Replace example IDs, phrases and dates, keep results small, and select only\n'
        'needed identifying fields. These examples do not request transcript excerpts;\n'
        'use [the excerpt guide](tool-selection.md#transcript-excerpts) for quotations.\n'
    ]
    for heading in HEADINGS:
        marker = f'### {heading}\n'
        if source.count(marker) != 1:
            raise ValueError(f'Expected exactly one canonical heading: {heading}')
        section = re.split(r'\n#{1,3} ', source.split(marker, 1)[1], maxsplit=1)[0]
        blocks = re.findall(r"```bash\ntl db es '(.*?)'\n```", section, re.S)
        if len(blocks) != 1 or section.count('```') != 2:
            raise ValueError(f'Unrecognized canonical example wrapper: {heading}')
        query = json.loads(blocks[0])
        if not isinstance(query, dict) or 'query' not in query:
            raise ValueError(f'Expected an ES query object: {heading}')
        chunks.append(f'## {heading}\n\n```json\n{json.dumps(query, indent=2, ensure_ascii=False)}\n```\n')
    return '\n'.join(chunks)


def validate(root: Path) -> None:
    plugin = root / PLUGIN
    for name in FILES:
        path = plugin / name
        if not path.is_file() or path.is_symlink() or not path.resolve().is_relative_to(plugin.resolve()):
            raise ValueError(f'Missing or unsafe plugin file: {name}')
    expected = render_examples((root / SOURCE).read_text())
    if (plugin / GENERATED).read_text() != expected:
        raise ValueError('Generated examples drifted; run python scripts/build_mcp_plugin.py --generate')
    manifest = json.loads((plugin / FILES[0]).read_text())
    if manifest['name'] != plugin.name or manifest['skills'] != './skills/' or manifest['mcpServers'] != './.mcp.json':
        raise ValueError('Plugin name or component paths do not match bundle')
    connection = json.loads((plugin / '.mcp.json').read_text())
    if connection != {'mcpServers': {'thoughtleaders': {'type': 'http', 'url': 'https://app.thoughtleaders.io/mcp'}}}:
        raise ValueError('Unexpected MCP connection configuration')
    marketplace = json.loads((root / '.agents/plugins/marketplace.json').read_text())
    entries = [p for p in marketplace['plugins'] if p['name'] == manifest['name']]
    if len(entries) != 1 or entries[0]['source'] != {'source': 'local', 'path': f'./{PLUGIN.as_posix()}'}:
        raise ValueError('Marketplace does not resolve to this plugin')
    skill = (plugin / 'skills/tl-mcp/SKILL.md').read_text()
    if not skill.startswith('---\nname: tl-mcp\n'):
        raise ValueError('Expected distinct tl-mcp skill name')
    if (root / 'skills/tl-mcp').exists():
        raise ValueError('MCP skill must not be in the CLI skill tree')
    for name in FILES:
        if not name.endswith('.md'):
            continue
        path = plugin / name
        for link in re.findall(r'\]\(([^)]+)\)', path.read_text()):
            if '://' in link:
                continue
            target = (path.parent / link.split('#')[0]).resolve()
            if not target.is_relative_to(plugin.resolve()) or target.relative_to(plugin.resolve()).as_posix() not in FILES:
                raise ValueError(f'Unpackaged reference in {name}: {link}')


def build_zip(root: Path, output: Path) -> str:
    validate(root)
    if output.resolve().is_relative_to((root / PLUGIN).resolve()):
        raise ValueError('Write upload artifacts outside the maintained plugin source')
    output.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(output, 'w', compression=zipfile.ZIP_STORED) as archive:
        for name in sorted(FILES):
            info = zipfile.ZipInfo(name, date_time=(1980, 1, 1, 0, 0, 0))
            info.create_system = 3
            info.external_attr = 0o100644 << 16
            archive.writestr(info, (root / PLUGIN / name).read_bytes())
    digest = hashlib.sha256(output.read_bytes()).hexdigest()
    output.with_suffix(output.suffix + '.sha256').write_text(f'{digest}  {output.name}\n')
    return digest


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--generate', action='store_true', help='Refresh generated examples from canonical CLI references')
    parser.add_argument('--output', type=Path, help='Write a deterministic upload ZIP after validation')
    args = parser.parse_args()
    if args.generate:
        (ROOT / PLUGIN / GENERATED).write_text(render_examples((ROOT / SOURCE).read_text()))
    validate(ROOT)
    if args.output:
        print(f'{build_zip(ROOT, args.output)}  {args.output}')
    else:
        print('MCP plugin references and generated content are current.')


if __name__ == '__main__':
    main()
